### ISSUE TITLE
Error loading "dtwainjni32u" library in a Java Project

### ISSUE THREAD

**Issue by borjafg** [dynarithmic/twain_library#17]
I created a project using eclipse (version 2020_06) and a JDK 8 (version 241 - 32 Bits). When I tried to load the library it gives me this error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\development\projects\ScannerTest\dlls\dtwainjni32u.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.dynarithmic.twain.DTwainJavaAPI.DTWAIN_JavaSysInitialize(DTwainJavaAPI.java:72)
	at com.dtwain.test.DTwainJavaCapDemo.runDemo(DTwainJavaCapDemo.java:14)
	at com.dtwain.test.DTwainJavaCapDemo.main(DTwainJavaCapDemo.java:75)
```

Using a program to search the dependencies of the library I saw it needs "dtwain32.dll".

![image](https://user-images.githubusercontent.com/6740268/111806848-b2404c00-88d2-11eb-8cde-03c044f483cf.png)

I took the library from your repository but it gives the same error.

I ran "DTWDEMO32.exe" and "DTWDEMO32U.exe" and both worked fine, so the problem must be in the java code or "dtwainjni32u.dll".

This is the java project I am using for testing to the issue. I used the source code from your repository.

[ScannerTest.zip](https://github.com/dynarithmic/twain_library/files/6172579/ScannerTest.zip)

And this is the configuration I used to launch the test.

![image](https://user-images.githubusercontent.com/6740268/111809833-ae61f900-88d5-11eb-8219-ec6021bd5207.png)

![image](https://user-images.githubusercontent.com/6740268/111809897-bfab0580-88d5-11eb-810e-ed73a4c89b27.png)

![image](https://user-images.githubusercontent.com/6740268/111809988-d3566c00-88d5-11eb-92a2-ff1d1c4fa971.png)

![image](https://user-images.githubusercontent.com/6740268/111810081-e8cb9600-88d5-11eb-9467-cd1cfe50ff7b.png)

![image](https://user-images.githubusercontent.com/6740268/111810322-2cbe9b00-88d6-11eb-8b89-32cb13c85ee1.png)

**Comment by dynarithmic** [comment]
It's been a while since I ran the Java binding, but the `dtwainjni32u.dll` has dependencies on `dtwain32u.dll`, not `dtwain32.dll`.  

![image](https://user-images.githubusercontent.com/1283116/111875030-16fcb480-896e-11eb-9906-ad7caf6eb2eb.png)

You probably need to have `dtwain32u.dll` available on the system path.

**Comment by borjafg** [comment]
Thanks.

Now it loads the library but it shows me another error in a cmd window when I run DTwainJavaCapDemo:

![image](https://user-images.githubusercontent.com/6740268/111877004-863fcc00-89a1-11eb-86b5-54612464f13c.png)


```
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10] ===>>> DTWAIN_GetVersionEx(lMajor=00DBF708, lMinor=00DBF70C, lVersionType=00DBF714, lPatchLevel=00DBF710)
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10]    ===>>> DTWAIN_GetVersionInternal(lMajor=00DBF708, lMinor=00DBF70C, lVersionType=00DBF714)
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10]    <<<=== DTWAIN_GetVersionInternal  1
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10] <<<=== DTWAIN_GetVersionEx  1
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10] ===>>> DTWAIN_GetStaticLibVersion()
[2021-03-20 17:16:10.467968] [0x0000389c] [trace]   [2021-03-20 17:16:10] <<<=== DTWAIN_GetStaticLibVersion  0
[2021-03-20 17:16:10.468969] [0x0000389c] [trace]   [2021-03-20 17:16:10] <<<=== DTWAIN_SetTwainLog  1
[2021-03-20 17:16:10.468969] [0x0000389c] [trace]   [2021-03-20 17:16:10] ===>>> DTWAIN_EnableMsgNotify(bSet=1)
[2021-03-20 17:16:10.468969] [0x0000389c] [trace]   [2021-03-20 17:16:10]    ===>>> DTWAIN_GetErrorString(lError=-1001, lpszBuffer=?, nMaxLen=1024)
[2021-03-20 17:16:10.469972] [0x0000389c] [trace]   [2021-03-20 17:16:10]    <<<=== DTWAIN_GetErrorString  0
[2021-03-20 17:16:10.469972] [0x0000389c] [trace]   [2021-03-20 17:16:10] ?

[2021-03-20 17:16:27.395720] [0x0000389c] [trace]   [2021-03-20 17:16:27]    ===>>> DTWAIN_SelectSource()
[2021-03-20 17:16:27.395720] [0x0000389c] [trace]   [2021-03-20 17:16:27]       ===>>> dynarithmic::SourceSelect(options=whichOption=1, productName=null, parentWindow=00000000, title=null, xPos=0, yPos=0, includeNames=null, excludeNames=null, nameMapping=null, options=0)
[2021-03-20 17:16:27.396717] [0x0000389c] [trace]   [2021-03-20 17:16:27]          ===>>> DTWAIN_GetErrorString(lError=-1001, lpszBuffer=, nMaxLen=1024)
[2021-03-20 17:16:27.396717] [0x0000389c] [trace]   [2021-03-20 17:16:27]          <<<=== DTWAIN_GetErrorString  0
```

![image](https://user-images.githubusercontent.com/6740268/111876827-d5d1c800-89a0-11eb-9a1c-aa1cfa062ba1.png)

![image](https://user-images.githubusercontent.com/6740268/111876753-75db2180-89a0-11eb-8f77-5de0ba5f32ee.png)

![image](https://user-images.githubusercontent.com/6740268/111876764-8db2a580-89a0-11eb-9731-f22bc60cbc03.png)

**Comment by dynarithmic** [comment]
Please see the [main page](https://github.com/dynarithmic/twain_library) for this error.  It is explained there.   There are text files that contains the resource strings, and DTWAIN does not find them.

**Comment by borjafg** [comment]
Thanks. Now the program runs without errors.

**Comment by dynarithmic** [comment]
Glad to be of help.

**Comment by dynarithmic** [comment]
Just as a note: The Java bindings may not have all of the recently added DTWAIN functions.  The only functions available are the native ones you see in DTwainJavaAPI.java.

To add any new functions requires changes to the C++ JNI layer and the Java interface.  I haven't had the time to update the Java bindings lately, but hopefully I can get around to doing so at some point.
